deploy:
  stage: deploy
  image: tiangolo/docker-with-compose:latest
  variables:
    DOCKER_HOST: tcp://91.210.168.214:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs"
  script:
    - mkdir -p $DOCKER_CERT_PATH
    - echo "$TLSCACERT" > $DOCKER_CERT_PATH/ca.pem
    - echo "$TLSCERT" > $DOCKER_CERT_PATH/cert.pem
    - echo "$TLSKEY" > $DOCKER_CERT_PATH/key.pem
    - docker-compose pull
    - docker-compose up -d
