build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    REPOSITORY: registry.gitlab.com/qrinef/crm-frontend-nuxt
  script:
    - docker login registry.gitlab.com -u $REGISTRY_LOGIN -p REGISTRY_TOKEN
    - docker build -t $REPOSITORY .
    - docker push $REPOSITORY
