build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    REGISTRY: registry.gitlab.com/qrinef/crm-frontend-nuxt
  script:
    - echo "$REGISTRY_TOKEN" | docker login -u "$REGISTRY_LOGIN" "$CI_REGISTRY" --password-stdin
    - docker build -t $REGISTRY .
    - docker push $REGISTRY
