build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  environment:
    name: production
    url: https://crm-backend-nest.qrinef.ru
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg API_URL=$CI_ENVIRONMENT_URL -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
