version: "3"

services:
  app:
    image: docker.pkg.github.com/qrinef/crm-frontend-nuxt/crm-frontend-nuxt:latest
    container_name: crm-frontend-nuxt
    expose:
      - 3000
    environment:
      VIRTUAL_HOST: crm-frontend-nuxt.qrinef.ru
      VIRTUAL_PORT: 3000

networks:
  default:
    external:
      name: nginx-proxy
